### PR TITLE
add note_add to contact whitelist

### PR DESCRIPTION
**Pull request by sylc**
added "note_add" to the whitelist of contact. This action was missing from the list.

### CODE REVIEW

**Review by bartboy011 — APPROVED** [review]
👍 Looks good to me!

**Comment by bartboy011** [comment]
@cristiangrama Could you take a look at this?

**Comment by bartboy011** [comment]
@sylc Thanks for the PR!

**Comment by sylc** [comment]
thanks for merging quickly. 👍  
When are you planning to release to npm?

**Comment by bartboy011** [comment]
@sylc We just published version `1.2.5` which includes your change!

**Pull request merged**
